server:
  port: 8090
spring:
  http:
    cors:
      allowed: true
      allowed-origins: '*'
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 1024MB
  datasource:
    #url: jdbc:mysql://localhost:5432/fudan_web_site?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=utf-8
    #username: root
    #password: Qyasd@123
    url: jdbc:mysql://localhost:3306/fudan_web_site?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: qingying2021
    druid:
      initial-size: 6
      max-active: 30
      max-wait: 60000
      max-open-prepared-statements: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-return: false
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: false
      time-between-log-stats-millis: 300000
      test-on-borrow: true
      validation-query: select 'x' from dual
app:
  upload:
    domain: http://test.com
    root: /website/upload

    #后台管理账号 admin003 123456