server:
  port: 9661
spring:
  http:
    cors:
      allowed: true
      allowed-origins: '*'
  datasource:
    #url: jdbc:mysql://120.26.58.188:3306/fudanWebSite?characterEncoding=utf8
    #username: root
    #password: 密码
    #username: root
    #password: qingying2021
    #url: jdbc:mysql://106.14.41.137:3306/fudan_web_site?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fudan_web_site?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qingying2021
    druid:
      initial-size: 3
      max-active: 30
      max-wait: 60000
      max-open-prepared-statements: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-return: false
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: false
      time-between-log-stats-millis: 300000
      test-on-borrow: true
      validation-query: select 'x' from dual
mybatis-plus:
  mapper-locations: com/cloud/cqc/service/**/mapper/xml/*.xml
  global-config:
    id-type: 0
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: CQCSecret
  expiration: 604800
  md5-key: CQCRKEY
app:
  init-password: 123456
  upload:
    domain: http://120.26.58.186/static/upload
    root: D:\ftpRoot\FuDanWebSite\dist\static\upload